services:

  frontamourconnect:
    container_name: frontamourconnect
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.node_frontend
      args:
        - NEXT_PUBLIC_PORT=${NEXT_PUBLIC_PORT}
        - IP_NOW_FRONTEND=${IP_NOW_FRONTEND}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - ${NEXT_PUBLIC_PORT}:${NEXT_PUBLIC_PORT}
    labels:
      # other
      - "traefik.enable=true"
      # DNS 1
      - "traefik.http.routers.frontamourconnect-1.rule=Host(`tubevideo.shop`)"
      - "traefik.http.routers.frontamourconnect-1.tls=true"
      - "traefik.http.routers.frontamourconnect-1.tls.certresolver=prodresolver"
      - "traefik.http.routers.frontamourconnect-1.entrypoints=websecure"
      - "traefik.http.routers.frontamourconnect-1.service=frontamourconnect"
      # DNS 2
      - "traefik.http.routers.frontamourconnect-2.rule=Host(`www.tubevideo.shop`)"
      - "traefik.http.routers.frontamourconnect-2.tls=true"
      - "traefik.http.routers.frontamourconnect-2.tls.certresolver=prodresolver"
      - "traefik.http.routers.frontamourconnect-2.entrypoints=websecure"
      - "traefik.http.routers.frontamourconnect-2.service=frontamourconnect"
      # loadbalancer
      - "traefik.http.services.frontamourconnect.loadbalancer.server.port=${NEXT_PUBLIC_PORT}"
      # middleware crowdsec
      - "traefik.http.routers.frontamourconnect.middlewares=crowdsec-frontamourconnect@docker"
      - "traefik.http.middlewares.crowdsec-frontamourconnect.plugin.crowdsec-bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec-frontamourconnect.plugin.crowdsec-bouncer.crowdseclapikey=${CrowdSec_BOUNCER_API_KEY}"
      # middleware redirect
      - "traefik.http.middlewares.test-redirectregex.redirectregex.regex=^https://www.tubevideo.shop/(.*)"
      - "traefik.http.middlewares.test-redirectregex.redirectregex.replacement=https://tubevideo.shop/$${1}"